package euler1to10;

// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.
public class Task2 {

//    4613732
    public static void main(String[] args) {
        final int BORDER =  4000000;
        int firstElement = 1;
        int secondElement = 2;

        int result = secondElement;

        for (int i = firstElement + secondElement; i <= BORDER; i += firstElement) {

            if (i % 2 == 0) {
                result+= i;
            }
            firstElement = secondElement;
            secondElement = i;
        }

        System.out.println(result);
    }
}
